CREATE TABLE outlets (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    google_map VARCHAR(500),
    CONSTRAINT unique_outlet UNIQUE (name, address)
);

INSERT INTO outlets (name, address, google_map) VALUES
('ZUS Coffee – Temu Business Centre City Of Elmina', 'No 5 (Ground Floor), Jalan Eserina AA U16/AA Elmina, East, Seksyen U16, 40150 Shah Alam, Selangor', 'https://maps.app.goo.gl/XduXnuUs4E2a1VE56'),
('ZUS Coffee – Spectrum Shopping Mall', 'Lot CW-5 Cafe Walk, Ground Floor Spectrum Shopping Mall Jalan Wawasan Ampang, 4, 2, Bandar Baru Ampang, 68000 Ampang, Selangor', 'https://maps.app.goo.gl/XPhXh6bgSb4pPaSz7'),
('ZUS Coffee – Bandar Menjalara', '37, Jalan 3/62a, Bandar Menjalara, 52200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/SoxNpkV3iGxmd4Rr7'),
('ZUS Coffee – Jabatan Peguam Negara,  Putrajaya', 'Bangunan Jabatan Peguam Negara AGC Persint 4, Lot 1, Level 1, Putrajaya 62100 Malaysia', 'https://maps.app.goo.gl/3jKWmERn8sC6ek6V7'),
('ZUS Coffee – LSH33, Sentul', 'G-11, Ground Floor, Laman Seri Harmoni (LSH33), No. 3, Jalan Batu Muda Tambahan 3, Sentul, 51100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/U7EbSxGQbjgtU6Qr8'),
('ZUS Coffee – Bandar Tun Hussein Onn, Cheras', 'No 48A Jalan Suarasa 8/4, Bandar Tun Hussein Onn, 43200 Cheras, Selangor', 'https://maps.app.goo.gl/9JbwtcN2q54sBjhk6'),
('ZUS Coffee – AEON BiG Wangsa Maju', 'Lot F1.11 (First Floor), AEON BiG Wangsa Maju, 6, Jalan 8/27A, Section 5, Wangsa Maju, 53300, Kuala Lumpur, Wilayah Persekutuan', 'https://maps.app.goo.gl/nuMteM6vU4YrhtHb9'),
('ZUS Coffee – Cheras Business Centre', 'No 6 Jalan 5/101C, Cheras Business Centre, 56100 Cheras, Kuala Lumpur', 'https://maps.app.goo.gl/hFRNP2j8XUnkfNEHA'),
('ZUS Coffee – Damansara Perdana, Petaling Jaya', '12-1 (Ground floor), Jalan PJU 8/5E, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor.', 'https://maps.app.goo.gl/Hj1Gu2MMHGabTZXb9'),
('ZUS Coffee – Bandar Damai Perdana, Cheras', 'No 19G (Ground floor), Jalan Damai Perdana 1/9b, Bandar Damai Perdana, 56000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/qnporqATyiphhS488'),
('ZUS Coffee – Desa Pandan, Ampang', 'No 35 (Ground Floor), Jalan 3/76D, Desa Pandan, 55100, Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://maps.app.goo.gl/ib8foAkecu9ePYRQ8'),
('ZUS Coffee – Kenanga Wholesale City, Jalan Gelugor', 'G-92 (GF 012.2) & G-93 (GF 012.1), Ground Floor, Kompleks Kenanga Wholesale City, No. 2, Jalan Gelugor, 55200 Kuala Lumpur', 'https://maps.app.goo.gl/YcqBi1cYaSaCHsHJ8'),
('ZUS Coffee – Giant Shah Alam Stadium', 'A14 – A16, Ground Floor, Giant Shah Alam Stadium, Persiaran Sukan, Seksyen 13, 40100 Shah Alam, Selangor', 'https://maps.app.goo.gl/V6jaEgHy2qcw1DJh6'),
('ZUS Coffee – Bintang Fairlane Residence', 'B�0�1 (Ground Floor), Block B, Retail 1, Bintang Fairlane, NO. 23, Jalan Padang Walter Grenier 55100 Kuala Lumpur', 'https://maps.app.goo.gl/mvZdYjtUQedZ75me9'),
('ZUS Coffee – Nadayu 801, Taman Subang Murni', 'Lot 08, Nadayu 801, Taman Subang Murni, 40150 Shah Alam, Selangor', 'https://maps.app.goo.gl/6J4ySUmhzK4ey9dWA'),
('ZUS Coffee – MAB Academy Campus Sepang', 'Level 1, MAB Academy (MABA Campus) Building, Southern Support Zone KLIA, 64000 Sepang, Selangor', 'https://maps.app.goo.gl/mLzPwsEm91VMgbhs7'),
('ZUS Coffee – Jalan Berangan, Port Klang', 'No 20(GF) Jalan Berangan, 42000 Port Klang, Selangor.', 'https://maps.app.goo.gl/JPkqNrEphcnqGZu76'),
('ZUS Coffee – Ampang Point', 'No 50(GF) Jalan Memanda 9, Selangor. Taman Dato Ahmad Razali, 68000 Ampang, Selangor', 'https://maps.app.goo.gl/EoDEnDH114wWbrLk9'),
('ZUS Coffee – Seksyen 3, Bandar Baru Bangi', '47-G, Jalan 3/69, Seksyen 3, 43650 Bandar Baru Bangi, Selangor', 'https://maps.app.goo.gl/JCF1Ug6dFCaiiVzS7'),
('ZUS Coffee – Seksyen 7, Bandar Baru Bangi', 'No.48G (Ground Floor), Jalan 7/7a, Seksyen 7, 43650 Bandar Baru Bangi, Selangor.', 'https://maps.app.goo.gl/y6AehkccGpJHt4Fx9'),
('ZUS Coffee – Desa Aman Puri, Kepong', 'No. 3-15A (GF), Jalan Desa 2/2, Desa Aman Puri, 52100 Kuala Lumpur.', 'https://maps.app.goo.gl/gU68hxYf1toPTHoR6'),
('ZUS Coffee – M Vertica, Cheras', 'No Lot G-10(GF) M Vertica Retail Shop, 555 Jalan Cheras, Taman Pertama, 56000 Kuala Lumpur.', 'https://maps.app.goo.gl/gxwDwJLy9CN4eKZS7'),
('ZUS Coffee – Pasaraya CS Bangi Avenue', 'Kiosk K10 & K11 (Ground Floor), No.1, Persiaran Bangi Avenue, Taman Bangi Avenue, 43000 Kajang, Selangor Darul Ehsan.', 'https://maps.app.goo.gl/cVNJDgm78ZcuzQwy8'),
('ZUS Coffee – Lorong Pandan Pertama 5, Ampang', 'SA-10-G, Lorong Pandan Pertama 5, Taman Pandan Utama, 68000 Ampang Jaya, Selangor', 'https://maps.app.goo.gl/g6F67nL4MK6bNaKg9'),
('ZUS Coffee – Edusentral, Setia Alam', 'VB-G-07 (Ground Floor), Edu Sentral, Jalan Setia Murni U13/51, Setia Alam Seksyen U13, 40170 Shah Alam, Selangor Darul Ehsan', 'https://maps.app.goo.gl/UojmkGDokTKHbgij9'),
('ZUS Coffee – Wangsa Walk Mall', 'GL-03A & FL-03A and GL-05 & FL-05, BL-03A & BL-05, Wangsa Walk Mall, Wangsa Permai, 53300 Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/HWofKJLBZCt23ckZ6'),
('ZUS Coffee – Uptown Damansara, Petaling Jaya', '44-G (Ground Floor), JALAN SS21/39, DAMANSARA UTAMA, 47400 PETALING JAYA, SELANGOR', 'https://maps.app.goo.gl/SGuUWhHHEBNd8mFWA'),
('ZUS Coffee – Bangsar Trade Centre', 'Lot E-1-2(A), Ground Floor, Tower E, Bangsar Trade Centre. Off Jalan Pantai Baru, 59200 Kuala Lumpur.', 'https://maps.app.goo.gl/1QrDViaDCQ7m5Dc58'),
('ZUS Coffee – BHPetrol Karak Highway', 'Lot 1173, Stesen Minyak BP Lebuhraya Karak Kuala Lumpur, Daerah Gombak, 53000 Kuala Lumpur', 'https://maps.app.goo.gl/rrkBGoVKpBATxEt89'),
('ZUS Coffee – KL Eco City Mall', 'G-12, Ground Floor, KL Eco City Mall, INC, 3, Jalan Bangsar, KL Eco City, 59200 Kuala Lumpur, Federal Territory of Kuala Lumpur', 'https://maps.app.goo.gl/kFzmFBpFo1N9Qyi58'),
('ZUS Coffee – Alam Budiman, Shah Alam', 'No 53-G, Jalan Pulau Lumut P U10/P, Alam Budiman, Seksyen U10, 40170 Shah Alam, Selangor', 'https://maps.app.goo.gl/ffTrhw66NZuooUKS8'),
('ZUS Coffee – Elmina Lakeside Mall', 'GF-95 & 96, Elmina Lakeside Mall, No.5 & No.7, Persiaran Garcinia, Seksyen U15, 40170 Shah Alam, Selangor Darul Ehsan', 'https://maps.app.goo.gl/R3BUrKfqbMsDcvyD7'),
('ZUS Coffee – Pinnacle Sri Petaling Mall', 'G-K-01, Ground Floor, Pinnacle Sri Petaling Mall, Jalan Radin Anum 1, Bandar Baru Sri Petaling, 57000 Kuala Lumpur, Malaysia', 'https://maps.app.goo.gl/NYqx1mry2ZT3v6WL6'),
('ZUS Coffee – Dataran Glomac, Kelana Jaya', 'C-G-05 (Ground Floor), Jalan SS 6/5b, Dataran Glomac, 47301 Petaling Jaya, Selangor.', 'https://maps.app.goo.gl/PbdUfc36FVxXzXz76'),
('ZUS Coffee – UOA Business Park, Shah Alam', 'Unit Lot- 13-03A, Level 1, UOA Business Park, No 1, Jalan Pengatucara U1/51A, Seksyen U1 40150 Selangor Darul Ehsan', 'https://maps.app.goo.gl/Pju2yTHLgw6Tqe7P6'),
('ZUS Coffee – Atria Shopping Gallery', 'Atria Shopping Mall, Kiosk CK9, Concourse Floor, Jalan SS 22/23, Damansara Jaya, 47400 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/JjyAvXoSL33VPd3p6'),
('ZUS Coffee – Lebuh Turi, Klang', 'Lot No. 88 (Ground Floor), Lebuh Turi, Taman Chi Liung, 41200 Klang, Selangor', 'https://maps.app.goo.gl/cMVfNAymsUxDVHWK6'),
('ZUS Coffee – Ground Floor, Menara IQ', 'Unit 001, Ground Floor, Menara IQ, TRX 55188 Kuala Lumpur', 'https://maps.app.goo.gl/BPGx2vU7o7WLXtUs6'),
('ZUS, Coffee Meets Pastry – 1 Utama Shopping Centre', 'Lot G601A, Ground Floor, 1 Utama Shopping Centre, 1, Lebuh Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/Qd3UY7VnZNVdPeQU9'),
('ZUS Coffee – Taman Segar Perdana, Cheras', 'No 07GF) Jalan Segar Perdana 2, Taman Segar Perdana, 43200 Cheras, Selangor.', 'https://maps.app.goo.gl/3ZVWQuWBvvk32DfV8'),
('ZUS Coffee – Sabak Bernam', 'No.100 (Ground Floor), Jalan Menteri, Pekan Sabak, 45200 Sabak Bernam, Selangor', 'https://maps.app.goo.gl/GfSJqhuBsUJbtr5M9'),
('ZUS Coffee – Jalan Kebun Nenas, Klang', 'No 47-G Jalan Kebun Nenas 7A/KS8, Bandar Putera 2, 41200 Klang, Selangor', 'https://maps.app.goo.gl/Bvkksy8u6HjkSVRZ7'),
('ZUS Coffee – Menara TH Perdana', 'Unit L02,Tingkat Bawah, Jln Sultan Ismail, Chow Kit, 50250 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/7uwonBiP8Jw9VPNXA'),
('ZUS Coffee – MRT Bandar Utama', 'MRT Bandar Utama (Kajang Line), Station Concourse area, Persiaran Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor.', 'https://maps.app.goo.gl/FzLWWCFfbpqx7mTB7'),
('ZUS Coffee – Micasa Shoppes, Jalan Tun Razak', 'Lot G.11 & Mezzanine, Micasa Shoppes, 368A, Jln Tun Razak, Taman U Thant, 55000 Kuala Lumpur, Wilayah Persekutuan', 'https://maps.app.goo.gl/QEMe5NRA75F4wNDS8'),
('ZUS Coffee – Wisma TH Plaza Sentral', 'L-01B, Jalan Stesen Sentral 5, Kuala Lumpur Sentral, 50470 Kuala Lumpur', 'https://maps.app.goo.gl/6q5uPX6uy64oBC2VA'),
('ZUS Coffee – Pertama Complex, Kuala Lumpur', 'Kiosk No. 3, Kompleks Pertama, Jalan Tuanku Abdul Rahman, 50100 Kuala Lumpur', 'https://maps.app.goo.gl/qaW4ZmnjGioUqLYV8'),
('ZUS Coffee – Pekan Kapar, Klang', 'No. 228 (Ground Floor), Jalan Besar KU/13, Pekan Kapar, 42200 Kapar, Selangor', 'https://maps.app.goo.gl/by7nC4Lsh7aMRusSA'),
('ZUS Coffee – Sri Rampai, Setapak', 'No.39 (Ground Floor), Jalan 45/26 Taman Sri Rampai, 53300 Kuala Lumpur.', 'https://maps.app.goo.gl/UFPhAXiUpmb2v9X57'),
('ZUS Coffee – Bloomsvale Shopping Gallery', 'G-018, Level Ground Floor, Bloomsvale Shopping Gallery, 137, Jalan Puchong, 58200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/uYE7LuvdEp2yugjXA'),
('ZUS Coffee – Bandar Mahkota Cheras', 'GK-01, BMC Mall. Jalan Temenggung 21/9, Bandar Mahkota Cheras, 43200 Cheras, Selangor.', 'https://maps.app.goo.gl/NJcrYqQpzVxSY3R1A'),
('ZUS Coffee – KL Traders Square', '51-G, KLTS, NO. 99, JALAN GOMBAK, SETAPAK, 53000, KUALA LUMPUR', 'https://maps.app.goo.gl/ovNcaWjp4BCQgJbp7'),
('ZUS Coffee – Bandar Kinrara 5, Puchong', 'No 10(GF), Jalan BK 5A/2C, Bandar Kinrara 5, 47180 Puchong, Selangor', 'https://maps.app.goo.gl/SFmvcBUEDf4GNZZd8'),
('ZUS Coffee – KPJ Kajang Specialist Hospital', 'KPJ Kajang Specialist Hospital, Jalan Cheras, Kampung Sungai Kantan, 43000 Kajang, Selangor.', 'https://maps.app.goo.gl/cV26tGNhZYm3Jtgm8'),
('ZUS Coffee – Kuala Kubu Baru', 'No.18(GF), Jalan Mat Kilau, Pekan Kuala Kubu Bharu, 44000 Kuala Kubu Baru, Selangor', 'https://maps.app.goo.gl/vfdaNXFcxBcmHrq16'),
('ZUS Coffee – Menara Axis, Petaling Jaya', 'Grd-05, Ground Floor, Menara Axis, No 2, Jalan 51A/ 223,46100 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/GLtte1nwwryXQqKC8'),
('ZUS Coffee – Central I-City', 'Lot L1-10A, Level One, Central I-City, No. 1, Persiaran Multimedia, Seksyen 7, Jalan Plumbum 7/102, I-City, 40000 Shah Alam, Selangor', 'https://maps.app.goo.gl/St1WubMeyce9k1Eh9'),
('ZUS Coffee – Taman Sri Muda', 'No.16-G (Ground Floor), Jalan Murni 25/61, Taman Sri Muda, 40400 Shah Alam, Selangor', 'https://maps.app.goo.gl/KJqteAwTt7SUEaik9'),
('ZUS Coffee – Alam Avenue 2, Shah Alam Seksyen 16', 'C-15-G, Jalan Serai Wangi L 16/L, Seksyen 16, Alam Avenue 2, 40200 Shah Alam, Selangor', 'https://maps.app.goo.gl/VweJD4e4SZETjWmD7'),
('ZUS Coffee – Kuchai Entrepreneurs Park', 'No. 29 (Ground Floor), Jalan 1/116 B, Off, Jalan Kuchai Lama, Kuchai Entrepreneurs Park, 58200 Kuala Lumpur.', 'https://maps.app.goo.gl/1DQNDZUjKwhAr89X7'),
('ZUS Coffee – Jalil Link 1, Bukit Jalil', 'No.20(GF), Jalan Jalil Jaya 2, Jalil Link, Bukit Jalil 57000 WP Kuala Lumpur', 'https://maps.app.goo.gl/GgafJATLe1djdh5z5'),
('ZUS Coffee – Menara Technip Energies', 'Menara Technip Energies, 38, Jalan Inai, Imbi, 55100 Kuala Lumpur, Federal Territory of Kuala Lumpur', 'https://maps.app.goo.gl/2qhwJWG5A8jf4poW7'),
('ZUS Coffee – Jakel Mall, Kuala Lumpur', 'Lot SC.02 & SC.03, Jakel Mall, Lot 159, Jakel Square Off, Jalan Munshi Abdullah, City Centre, 50100 Kuala Lumpur', 'https://maps.app.goo.gl/SinZDdy8GsWQohhr6'),
('ZUS Coffee – Anggun City, Rawang', 'Lot 40-1, Pusat Komersial Anggun City, 1, Jalan Anggun City 1, Taman Anggun, 48000 Rawang, Selangor', 'https://maps.app.goo.gl/pNRC9HwFT298kdUaA'),
('ZUS Coffee – Olive Business Park, Seri Kembangan', 'No 36 (LG), Jalan BS 1/3, Pusat Perdagangan Olive Hill, Taman Bukit Serdang Seksyen 1, 43300 Seri Kembangan, Selangor.', 'https://maps.app.goo.gl/ecQ6XHq5W4oN447aA'),
('ZUS Coffee – Bukit Tinggi 1', 'No.26-G, Lorong Batu Nilam 3a, Bandar Bukit Tinggi 41200 Klang', 'https://maps.app.goo.gl/zM1roarwqnoHVk7YA'),
('ZUS Coffee – CALTEX Eco Ardence', 'No. 2, Jalan Eco Ardence U12/36, Seksyen U12 40170, Shah Alam, Selangor', 'https://maps.app.goo.gl/kZxYiKdfidnaDftEA'),
('ZUS Coffee – Jalan Seri Mas 1, Hulu Langat', 'No.33 (Ground Floor), Jalan Seri Mas 1, Taman Seri Emas, 43100 Hulu Langat, Selangor.', 'https://maps.app.goo.gl/zGHiZHjhXuJDtNvo6'),
('ZUS Coffee – Pekan Semenyih', 'No.40 (Ground Floor), Jalan Pasar Baru, Pekan Semenyih, 43500 Semenyih, Selangor.', 'https://maps.app.goo.gl/mT7LLGgzhHkHxAUbA'),
('ZUS Coffee – Solaris Mont Kiara', 'Lot K-OG-14, Soho KL Mont Kiara, No. 2, Jalan Solaris, Solaris Mont Kiara, 50480, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/Nc3SFsKZyhSSgaaF8'),
('ZUS Coffee – Cyberview 23A, Cyberjaya', 'Cyberview 23A, Persiaran APEC Cyber 6, 63000 Cyberjaya Selangor', 'https://maps.app.goo.gl/65eKzyJ3AYr7Ufc26'),
('ZUS Coffee – Monash University Malaysia', '3124C, Lepak Place, Monash University Malaysia, Jalan Lagoon Selatan, 47500 Bandar Sunway, Selangor Darul Ehsan', 'https://maps.app.goo.gl/yiZH7dYYP8vJFZsi7'),
('ZUS Coffee – Semua House', 'GF.04, Ground Floor, Semua House, Jalan Bunus 6, City Centre, 50100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/cyFk3f3wuVoRiVCi8'),
('ZUS Coffee – Southville City', 'A�G�09 (Ground Floor), Savanna Lifestyle Retail Jalan BBLS 2, Bandar Baru Lembah Selatan, 43800 Dengkil, Selangor', 'https://maps.app.goo.gl/D4ZHpH55QcfbryDy5'),
('ZUS Coffee – Sekinchan', 'No.15 (Ground Floor), Jalan Peria, Pekan Sekinchan, 45400 Sekinchan, Selangor', 'https://maps.app.goo.gl/wFX1izTnAqp11QqQ7'),
('ZUS Coffee – Kompleks PKNS Shah Alam', 'Lot G-6 (Ground Floor), Kompleks PKNS Shah Alam, Persiaran Tasik, Seksyen 14, 40000 Shah Alam, Selangor', 'https://maps.app.goo.gl/11uRprMV9ixudpHT8'),
('ZUS Coffee – Shah Alam Seksyen 18', '15G (Ground Floor), Jalan Pinang B 18/B, Seksyen 18, 40200 Shah Alam, Selangor', 'https://maps.app.goo.gl/tV4tVt5hoCqVVS7d6'),
('ZUS Coffee – SAMA Square', 'G-02 & 02(E), Ground Floor, Same Square, Jalan 1/23c, Kampung Baru Air Panas, 53200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://maps.app.goo.gl/EzptbL3cArET9Nw1A'),
('ZUS Coffee – GM Klang', 'A-G-13, Ground Floor, Wholesale City Gm Klang, Jalan Kasuarina 1, Bandar Botanik, 41200 Klang, Selangor', 'https://maps.app.goo.gl/KpWWdYpXUwHVqHk9A'),
('ZUS Coffee – Prima Saujana, Kajang', 'No.20 (GF), Jalan Prima Saujana 1/1A, Prima Saujana 43000 Kajang Selangor.', 'https://maps.app.goo.gl/eEyMwE9Vq4HixWfL6'),
('ZUS Coffee – AEON Mall Bukit Tinggi', 'Lot F26, AEON Bukit Tinggi Shopping Centre, 1, Persiaran Batu Nilam 1, KS6, 41200, Selangor', 'https://maps.app.goo.gl/ciHTbpy7nFNH1xbQA'),
('ZUS Coffee – Shah Alam Seksyen 20', 'No 18, Jalan Singa D 20/D, Seksyen 20, 40300 Shah Alam, Selangor', 'https://maps.app.goo.gl/NJWvjTigi6rz1STG7'),
('ZUS Coffee – You City III Cheras', 'Lot no G-AP-8, Jalan Persiaran You City,Taman Suntex, 43200 Cheras, Selangor', 'https://maps.app.goo.gl/MKWRhERopFZX9iwV8'),
('ZUS Coffee – Menara UOA Bangsar', 'Lot LGF-8, Lower Ground Floor, 5, Jalan Bangsar Utama 1, Bangsar, 59000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/9GFMf9ozWFEwVB3Q6'),
('ZUS Coffee – TTDI Jaya, Shah Alam', 'No.33 (Ground Floor), Jalan Opera F U2/F, Taman TTDI Jaya, Seksyen U2, 40150 Shah Alam.', 'https://maps.app.goo.gl/y6JS8BiUbaStYPDPA'),
('ZUS Coffee – Citta Mall', 'G-48 7 G-48A, Ground Floor, Citta Mall, 1, Jalan PJU 1a/48, Ara Damansara, 47301 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/AGW7mvcrQhFBKF2S6'),
('ZUS Coffee – Cubic Botanical, Pantai Dalam', 'No. R2-1 (Lower Ground Floor), Residensi Rimba Pantai Dalam, No. 6, Jalan Pantai Sentral 3, Pantai Dalam, 59200 Kuala Lumpur', 'https://maps.app.goo.gl/2CFVnP1RUU76rsmZ8'),
('ZUS Coffee – TTDI Grove Kajang', 'No. 26, JALAN TTDI GROVE 1/1, 43000 KAJANG, SELANGOR', 'https://maps.app.goo.gl/9RQRxmiGig3X6BXF9'),
('ZUS Coffee – Jenjarom', 'No. 37 (Ground Floor), Jalan 2/1, Taman Seri Jaromas, 42600 Jenjarom', 'https://maps.app.goo.gl/jij7okFL6ZQ6oDj38'),
('ZUS Coffee – Suasana PjH Presint 2', 'Unit A-G-R10 & A-G-R11, Block A, Suasana PjH, Jalan Tun Abdul Razak, Presint 2, 62100 Putrajaya', 'https://maps.app.goo.gl/KuSAsowCiPCM3ZaY7'),
('ZUS Coffee – Plaza Low yat', 'Plaza Low Yat, Lot LG-04 & 05, Lower Ground Floor, 7, Jalan Bintang, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/hP7wXLwkdTDEP9Jk8'),
('ZUS Coffee – Selera Putra, Souq Putrajaya', 'Lot G-005, Selera Putra, Souq Putrajaya, Presint 1, 62000 Putrajaya', 'https://maps.app.goo.gl/u8mwJJX78gsH9Cd66'),
('ZUS Coffee – Plaza Shah Alam', 'S19, Second Floor, Jalan Tengku Ampuan Zabedah E 9/E, Seksyen 9, 40100 Shah Alam, Selangor', 'https://maps.app.goo.gl/jmCaSVSHEAZX1uCPA'),
('ZUS Coffee – Vista Bangi, Jalan Reko', '1-06 (Ground Floor) Vista Bangi, Jalan Reko, 43000 Kajang, Selangor.', 'https://maps.app.goo.gl/cjtSfXE8JLt3kB6K6'),
('ZUS Coffee – Kipmall Bangi', '1K-03A, Level 1, No. 1 Jalan Medan Bangi Business Park Bangi Golf Resort) Off, Persiaran Kemajuan, Seksyen 6, 43650 Bandar Baru Bangi, Selangor', 'https://maps.app.goo.gl/uR1tJeAs3S9T1Hgy5'),
('ZUS Coffee – Universiti Malaya Centre for Continuing Education', 'VIP Dining, Cyberview 23, Jalan Teknokrat 3, Cyber 4, 63000 Cyberjaya, Selangor', 'https://maps.app.goo.gl/r9fWQegqWYNN5YGh9'),
('Ready-To Zus – Holiday Inn Express Hotel KL', 'Lot G01, Ground Floor, 84, Jalan Raja Chulan, Kuala Lumpur, 50200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/tTGVQUum8VZxHCiDA'),
('ZUS Coffee – MSU Medical Centre', 'Lot A01 (Ground Floor), MSU Medical Centre, University Drive, Off Persiaran Olahraga, Seksyen 13, 40100 Shah Alam, Selangor.', 'https://maps.app.goo.gl/jqLkNUJLJTSDrwiv5'),
('ZUS Coffee – Bandar Teknologi Kajang', 'No. G-8 (Ground Floor), Jalan 1/2, HILLPARK RESIDENCE, Seksyen 1 Bandar Teknologi Kajang, 43500 Semenyih, Selangor', 'https://maps.app.goo.gl/9cNsY6ftsn1d5rgx9'),
('ZUS Coffee – Menara VSQ Petaling Jaya', 'B03, Ground Floor, VSQ@PJ City Centre, Jalan Utara, 46200 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/PAvN2P4C7TSVRLiH9'),
('ZUS Coffee – Damansara Damai', 'L-013 (Ground Floor), Vista Shop, Jalan PJU 10/2A, Damansara Damai,47830 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/x3vfoWpBpRLG9K327'),
('ZUS Coffee – AEON Mall Cheras Selatan', 'KF3 & KF5, First Floor, Aeon Mall Cheras,�Selatan, Jalan Cheras Perdana Cheras, 43200,�Balakong, Selangor', 'https://maps.app.goo.gl/UrdwdN3cYSCCSuqB7'),
('ZUS Coffee – Setia Prima, Setia Alam', '8-1-2 (Ground Floor), Jalan Setia Prima P U13/P, Setia Alam, 40170 Shah Alam, Selangor', 'https://maps.app.goo.gl/1i1djZnUqsuTjtip7'),
('ZUS Coffee – The Glenz @Glenmarie', 'G-3B (Ground Floor), Subplace Boulevard Pusat Kormersil Vestland, No.6, Jalan Juruanalisis U1/35, Seksyen U1, 40150 Shah Alam, Selangor Darul Ehsan', 'https://maps.app.goo.gl/qyNRDn9vdyN7ebpa9'),
('ZUS Coffee – Puchong Utama', 'A-G-9 (Ground Floor), Block A, Dataran Puchong, Jalan PU 7/1, Taman Puchong Utama, 47140 Puchong, Selangor', 'https://maps.app.goo.gl/JFR4PpoU3195PJiQ7'),
('ZUS Coffee – Sunway Pyramid', 'Lot LG2.37, Level LG2, Sunway Pyramid, 3, Jalan PJS 11/15, Bandar Sunway, 47500 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/gEZekwMHNSMr48rM8'),
('ZUS Coffee – Setapak Central Mall', 'GK-08, Ground Floor, 67, Jln Taman Ibu Kota, Taman Danau Kota, 53300 Kuala Lumpur, Wilayah Persekutuan', 'https://maps.app.goo.gl/Bm11m4TsgbU4vHuN7'),
('ZUS Coffee – The Exchange TRX', 'Lot C.98.0, The Exchange TRX, Persiaran TRX, Tun Razak Exchange, 55188 Kuala Lumpur, Wilayah Persekutuan', 'https://maps.app.goo.gl/dF2G1ifX7ZNim34X9'),
('ZUS Coffee – Taman Sri Manja', 'No.25, Jalan PJS 3/46, Taman Sri Manja, 46000 Petaling Jaya', 'https://maps.app.goo.gl/NC5h4Ka5GpkNqZXv7'),
('ZUS Coffee – Eco Grandeur', 'No 18-G (Ground Floor), Jalan Eco Grandeur 1/9A, Eco Granduer, 42300, Bandar Puncak Alam, Selangor', 'https://maps.app.goo.gl/Ri16uBrxZcHrzipp6'),
('ZUS Coffee – Jaya Shopping Centre', 'Lot G-01, Jaya Shopping Centre, Jalan 14/17, Seksyen 14, 46100 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/PPdekSrAX9qRBJPaA'),
('ZUS Coffee – Eco Majestic Semenyih', 'Lot 47-1, Jalan Eco Majestic 10/1A, 43500 Semenyih, Selangor.', 'https://maps.app.goo.gl/5do85BzjhSHZQqGd8'),
('ZUS Coffee – Gateway@KLIA2 (Departure Hall, Level 3)', 'Lot L3-44A, Level 3, gateway@KLIA2, Lbh KLIA, 43900 KLIA, Selangor', 'https://maps.app.goo.gl/zokxx7yUmHcStc978'),
('ZUS Coffee – Gateway@KLIA2 (Arrival Hall, Level 2)', 'Lot No. L2-90B, Level 2, gateway@KLIA2, Lbh KLIA, 43900 Klia, Selangor', 'https://maps.app.goo.gl/ix7SbeVWTn9Ya3JS7'),
('ZUS Coffee – Taipan USJ', 'No. 9 (Ground Floor), Jalan USJ 10/1E, Taipan Business Centre, 47620, Subang Jaya, Selangor', 'https://maps.app.goo.gl/ypaC1vcYetCYs3aV8'),
('ZUS Coffee – Sunway Velocity Mall', 'Lot 1-22, First Floor, Lingkaran SV2, Sunway Velocity Mall, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/tSr4cVgTudc9g7RKA'),
('ZUS Coffee – Sapura Lot 91 KLCC', 'Lot C-17, Level Concourse, Permata Sapura, Kuala Lumpur City Centre, 50088 Kuala Lumpur.', 'https://maps.app.goo.gl/7jfFcmfhtje1aJWr8'),
('ZUS Coffee – Taman Myra Meranti, Puchong', 'No. 8A (Ground Floor), Jalan MM4, Taman Myra Meranti, 47120 Puchong, Selangor Darul Ehsan', 'https://maps.app.goo.gl/T2FaCc1iy6ptTeor8'),
('ZUS Coffee – OUG Parklane', 'A1-0-12 (Ground Floor), OUG Parklane, Jalan 1/152, Taman OUG Parklane, 58200 Kuala Lumpur', 'https://maps.app.goo.gl/W24LoGds3JoiD3m37'),
('ZUS Coffee – Centro Mall', 'Lot GK105, Ground Floor, Centro Mall, 8, Jalan Batu Tiga Lama, Kawasan 16, 41300 Klang, Selangor', 'https://maps.app.goo.gl/PNyXbe5UZ439yJQj9'),
('ZUS Coffee – Lotus’s Klang', 'Lot GK14. KS 6, 3, Jalan Batu Nilam 6, Bandar Bukit Tinggi 1, 41200 Klang, Selangor.', 'https://maps.app.goo.gl/6rScsK1tKDm6Mcac6'),
('ZUS Coffee – Pavilion Damansara Heights', 'Lot 2.13.01. Level 2. No. 3, Jalan Damanlela, Pavilion Damansara Heights 50490 Kuala Lumpur.', 'https://maps.app.goo.gl/TqbHh3pMfNtRj4ht9'),
('ZUS Coffee – Shaftsbury Square', 'Level P1-23, Lot 2350, Shaftsbury Square, Cyber 6, 63000 Cyberjaya, Selangor', 'https://maps.app.goo.gl/rEPRLDbi6WzySivA6'),
('ZUS Coffee – SS2', 'No.5, Jalan SS2/67, SS2, 47300 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/bWF7JyTj4fsrvduv8'),
('ZUS Coffee – Sunway Velocity Two', 'Lot VS1-G-01, Sunway Velocity Two, Jalan Peel, Seksyen 90, 55100 Wilayah Persekutuan Kuala Lumpur.', 'https://maps.app.goo.gl/cpAihjdHZWuwS8fg8'),
('ZUS Coffee – Kidzania Kuala Lumpur', 'Curve NX, Jalan PJU 7/5, Mutiara, Damansara 47810 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/y8ftJcN4VPpD37U8A'),
('ZUS Coffee – Seventeen Mall', '998, Jalan 17/38, Seksyen 17, 46400 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/wg2ZfHJZQJP5gcnm7'),
('ZUS Coffee – SHELL Cyberjaya Autoville', 'Stesen Minyak Shell Autoville, Persiaran Mutilmedia, Cyber 10, 63000, Cyberjaya, Selangor', 'https://maps.app.goo.gl/69dHq3DgYtq3h3Kj6'),
('ZUS Coffee – Cybersouth Dengkil', 'No 35-G, Jalan PP 1/1, Park Place 1, Cybersouth, 43800 Dengkil, Selangor', 'https://maps.app.goo.gl/KJGBzSUYVHKFyxTs6'),
('ZUS Coffee – UCSI University KL', 'Lot 6, Block G, Ground Floor, UCSI University, No. 1, Jalan Menara Gading, UCSI Heights (Taman Connaught), 56000 Cheras, Kuala Lumpur.', 'https://maps.app.goo.gl/8nSgs6vCWKjW4MCR8'),
('ZUS Coffee – Avenue K', 'Lot C-6, Level Concourse, Avenue K, 156 Jalan Ampang, 50450 Kuala Lumpur.', 'https://maps.app.goo.gl/m5H6LUwbe4C68hQX9'),
('ZUS Coffee – Centrepoint Bandar Utama', 'LOT F103, First Floor, Centrepoint Bandar Utama, 3, Lebuh Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor', 'https://maps.app.goo.gl/2m3UHhhCWzcUGVi18'),
('ZUS Coffee – Setiawangsa', 'No 30-G (G-Floor), Jalan Setiawangsa 10 (10/55A), Taman Setiawangsa, 54200, WP Kuala Lumpur', 'https://maps.app.goo.gl/EDT9DtreNCn4rwmm8'),
('ZUS Coffee – Sungei Wang Plaza', 'Lot PK-5, Sungei Wang Plaza, Jalan Sultan Ismail, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://maps.app.goo.gl/dV42oSX7g5ekeQZq8'),
('ZUS Coffee – Universiti Kebangsaan Malaysia (Bangunan Pusanika)', 'Aras Satu, Bangunan Pusanika, Universiti Kebangsaan Malaysia, 43600 Bangi, Malaysia', 'https://goo.gl/maps/aaGcJeiphnfkk4DHA'),
('ZUS Coffee – Tower 8, Horizon 2, Bangsar South', 'Office 2, Ground Floor, Tower 8, Bangsar South City, Jalan Kerinchi, Kuala Lumpur.', 'https://goo.gl/maps/CE2q8A1rqUfLnF4SA'),
('ZUS Coffee – Eco Sky', 'G-30, Eco Sky, No. 972, Batu 6 1/2, Jalan Ipoh, 68100, Kuala Lumpur', 'https://goo.gl/maps/TA6HUrJFqjFiR7NX9'),
('ZUS Coffee – Berjaya Times Square', 'Berjaya Times Square, Lot LG-18C-03A, 1, Jln Imbi, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://goo.gl/maps/FpQtqDUj872Mufkd7'),
('ZUS Coffee – Alamanda Putrajaya', 'Lot G22, Ground Floor. Jalan Alamanda, Presint 1, 62000 Putrajaya, Wilayah Persekutuan Putrajaya.', 'https://goo.gl/maps/PGaneH9TTMDoakEK7'),
('ZUS Coffee – INTI International College Subang', 'Cafeteria Level 1, Block B, INTI International College Subang Campus, No 3, Jalan SS15/8, 47500 Subang Jaya, Selangor.', 'https://goo.gl/maps/SJ84L8pCBgH8zvxH9'),
('ZUS Coffee – Bandar Country Homes Rawang', 'No. G-16, Avia Plus, Jalan Desa Utama, Bandar Country Home, 48000 Rawang, Selangor', 'https://goo.gl/maps/nQGL8njPA1s4Y6jD7'),
('ZUS Coffee – Melawati Mall', 'Lot L1-K1, Melawati Mall, Jalan Bandar 12, Taman Melawati, 53100 Kuala Lumpur, Selangor', 'https://goo.gl/maps/T16Urjiiw11yjNer5'),
('ZUS Coffee – IOI Boulevard', 'B-G-13A (Ground Floor), IOI Boulevard, Jalan Kenari 5, Bandar Puchong Jaya, 47100 Puchong, Selangor.', 'https://goo.gl/maps/2HJnduG8ue4t45MZ8'),
('ZUS Coffee – Pekan Meru', '195, Jalan Meru Batu 6 1/2, Pekan Meru, 41050 Klang, Selangor', 'https://goo.gl/maps/KGo6jdjPNHe2a2j1A'),
('ZUS Coffee – Desa Petaling', '29, Jalan 3/125D, Desa Petaling 57100 Kuala Lumpur', 'https://goo.gl/maps/UfEC9rJBXdkkJymV8'),
('ZUS Coffee – Jade Hills Kajang', 'No 54-1, Jalan Dataran Jade 6, Dataran Jade, Jade Hills, 43000 Kajang, Selangor', 'https://goo.gl/maps/TfmPQdoZ9MG6uytz6'),
('ZUS Coffee – Bandar Tasik Puteri', 'No 82-G-A, Ground Floor, Jalan 7A/2, Bandar Tasik Puteri, 48000 Rawang, Selangor', 'https://goo.gl/maps/8rPEmN2RWEr2nKtr5'),
('ZUS Coffee – Bandar Sunway', 'No 27 (Ground Floor), Jalan PJS 11/28b, Sunway Metro Bandar Sunway, 46150 Petaling Jaya, Selangor', 'https://goo.gl/maps/UoPUbgiicKqwZM8K7'),
('ZUS Coffee – Cheras Leisure Mall', 'Lot L1-24, Leisure Mall, Jalan Manis 6, Taman Bukit Segar, 56100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://goo.gl/maps/kZMrsniabj6ajf7w8'),
('ZUS Coffee – Pearl Point Shopping Mall', 'LOT F-25. Menara Pearl Point 2 No. 2A, Jalan Sepadu, Off, Jln Klang Lama, 58200 Kuala Lumpur.', 'https://goo.gl/maps/RBFn4hcFJg4MpVqf8'),
('ZUS Coffee – Empire Shopping Gallery', 'LK-07, Level Lower Ground, Empire Shopping Gallery, Jalan SS16/1, 47500 Subang Jaya, Selangor Darul Ehsan', 'https://goo.gl/maps/rTq2Mxwc9xTKk3zc9'),
('ZUS Coffee – CALTEX Sungai Choh', 'PT 20499 (Lot 1493), Kampung Stesen, Sungai Buaya, 48000 Sungai Choh, Selangor Darul Ehsan.', 'https://goo.gl/maps/m9mA5w5jBNCcCczS7'),
('ZUS Coffee – Teluk Pulai', 'No.198 (Ground floor), Jalan Teluk Pulai, 41000 Klang, Selangor', 'https://goo.gl/maps/XTcn1fpDW94nPiTj8'),
('ZUS Coffee – PJ New Town', '10 (Ground Floor), Jalan 52/18, PJ New Town, 46200 Petaling Jaya, Selangor', 'https://goo.gl/maps/vprqmf1SbUoYNUs2A'),
('ZUS Coffee – KSL Esplanade Mall', 'LOT G053A, Ground Floor, No 2, Jalan Langat KS9, Bandar Bestari, 42500 Klang, Selangor', 'https://goo.gl/maps/MyjQQYEm8CoenS9U8'),
('ZUS Coffee – Da Men Mall', 'LG-25, Lower ground. 1, Persiaran Kewajipan, Usj 1, 47600 Subang Jaya, Selangor.', 'https://goo.gl/maps/Jw5aNpp3ad92Gopx9'),
('ZUS Coffee – University of Malaya', 'Locker Room (Ground Floor), Bangunan Perpustakaan Utama, University of Malaya, Lembah Pantai, 50603 Kuala Lumpur', 'https://goo.gl/maps/xm13sfWxCYfV1Exi8'),
('ZUS Coffee – University of Nottingham', 'Block H (Ground Floor), Student Association Building, Jalan Broga, 43500 Semenyih, Selangor Darul Ehsan', 'https://goo.gl/maps/khVM8oopnLEYDMLA8?coh=178572&entry=tt'),
('ZUS Coffee – Suria KLCC', 'Lot No. OS301 , Level 3, Suria KLCC, Persiaran Petronas, Kuala Lumpur City Centre, 50088 Kuala Lumpur', 'https://goo.gl/maps/ARggtH6kcQrkYHvd9'),
('ZUS Coffee – KL Gateway', 'Lot G.15 & G.16. KL Gateway Mall. 2, Jalan Kerinchi, Kampung Kerinchi, 59200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://goo.gl/maps/gAD6wBjcKucowH6B7'),
('ZUS Coffee – AEON Mall Wangsa Maju Alpha Angle', 'Lot F37. Jalan R1, Seksyen 1, Bandar Baru Wangsa Maju 53300 Kuala Lumpur.', 'https://goo.gl/maps/aofzy7oNitKgUVr4A?coh=178572&entry=tt'),
('ZUS Coffee – KLIA 1 Departure Hall', 'Lot CPD 3 A06, Gate A, Contact Pier Domestic KLIA, Kuala Lumpur International Airport, 64000 Sepang, Selangor Darul Ehsan.', 'https://goo.gl/maps/Tp6HjUUm8euMfajn6?coh=178572&entry=tt'),
('ZUS Coffee – M3 Shopping Mall', 'GK-10a & GK-10b, Jln Madrasah, Taman Melati, 53100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://goo.gl/maps/qjywrDrnqUGu9wbu5'),
('ZUS Coffee – Xiamen University Malaysia', 'A3 Library Cafe – GF, Xiamen University Malaysia, Jalan Sunsuria, Bandar Sunsuria, 43900 Sepang, Selangor.', 'https://goo.gl/maps/ZotrA6JJXknKzcAe9'),
('ZUS Coffee – Skypark Terminal', 'Lot No. G10B, Ground Floor, Skypark Terminal, Sultan Abdul Aziz Shah Airport, 47200 Subang, Selangor', 'https://goo.gl/maps/kQxq7pmLMEijYPvf9'),
('ZUS Coffee – Jaya One Mall', '100-P2.017 The School, Jaya One. 72A, Jln Profesor Diraja Ungku Aziz, Seksyen 13, 46200 Petaling Jaya, Selangor.', 'https://goo.gl/maps/PpDnAo6G1b4qmmw89'),
('ZUS Coffee – AEON Mall Metro Prima Kepong', 'LOT KF2. 1, Jalan Metro Prima, Taman Kepong, 52100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://goo.gl/maps/v1xUPJjziuK1fz8m6'),
('ZUS Coffee – Taman Bukit Anggerik', 'No.14 (Ground Floor), Jalan 34/154, Taman Bukit Anggerik, 56000 Kuala Lumpur', 'https://goo.gl/maps/PvRSFt1uTHd7vgrTA'),
('ZUS Coffee – AEON Mall Taman Maluri', 'Lot KF2. Jalan Jejaka, Maluri, 55100 Cheras, Wilayah Persekutuan Kuala Lumpur', 'https://goo.gl/maps/kZJHiwMJ8q6CciYo7'),
('ZUS Coffee – AEON Mall Bukit Raja', 'Lot G23, Bukit Raja Shopping Centre, Persiaran Bukit Raja 2, Bandar Baru Klang, 41150 Klang, Selangor.', 'https://goo.gl/maps/eNPD1wjJiYyxMgvE7'),
('ZUS Coffee – Taman Desa Setapak', 'No.37 (Ground Floor), Jalan 1/27B, Desa Setapak, 53300, Kuala Lumpur', 'https://goo.gl/maps/g5CwwuxBkz24D86u8'),
('ZUS Coffee – Taman Kosas', 'No 21 (Ground Floor), Jalan Kosas 1/2, Taman Kosas, 68000 Ampang, Selangor Darul Ehsan.', 'https://goo.gl/maps/PBCMtrnfNQp1iwc57'),
('ZUS Coffee – Putrajaya Presint 15', 'No 43 (Ground Floor), Jalan Diplomatik, Presint Diplomatik, 62050 Putrajaya, Wilayah Persekutuan Putrajaya', 'https://goo.gl/maps/LWyKNHec3hn7GTRKA'),
('ZUS Coffee – Bandar Sungai Long', 'No 19, Ground Floor, Jalan SL 1/4, Bandar Sungai Long, 43000 Kajang, Selangor', 'https://goo.gl/maps/JUW33rY5syUx5wPJ9'),
('ZUS Coffee – Quayside Mall', '1FK-07, First Floor. Quayside Mall. Gamuda Kemuning, 25.7, Persiaran Freesia, 42500 Telok Panglima Garang, Selangor.', 'https://goo.gl/maps/eHojDSUCoDMikY7S8'),
('ZUS Coffee – MYDIN USJ Subang Jaya', 'Lot GSRU-24,GSRU-25, Ground Floor level, MYDIN Subang Jaya, Persiaran Subang Permai, USJ 1, 47500 Subang Jaya, Selangor', 'https://goo.gl/maps/Xx5HyDKByC969rev8'),
('ZUS Coffee – Temu @ City Of Elmina', 'No 5 (Ground Floor), Jalan Eserina AA U16/AA, Elmina East, Seksyen U16, 40150 Shah Alam, Selangor Darul Ehsan.', 'https://goo.gl/maps/o3iKTrg6rGuo7Nh77'),
('ZUS Coffee – BMC Mall', 'GK-01, BMC Mall. Jalan Temenggung 21/9, Bandar Mahkota Cheras, 43200 Cheras, Selangor.', 'https://goo.gl/maps/M15crMMpR47xBeXEA'),
('ZUS Coffee – Nu Sentral Mall', 'Lot CC.04A. 201, Jalan Tun Sambanthan, Brickfields, 50470 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://goo.gl/maps/NJDM3kBomXgK1x9h7'),
('ZUS Coffee – Pandan Indah', 'No. 15G (Ground Floor), Jalan Perubatan 2, Pandan Indah, 55100, Kuala Lumpur.', 'https://goo.gl/maps/sAaiQ45dXvkmK9XY6'),
('ZUS Coffee – Majestic Maxim Residensi Tmn Bkt Cheras', 'No.LG-03, Residensi Majestic Maxim, 45, Jalan 9, Taman Bukit Cheras, 56000 Kuala Lumpur', 'https://goo.gl/maps/ewWYcrKErCVrR8A5A'),
('ZUS Coffee – Quill City Mall', 'LG-23A. 1018, Jln Sultan Ismail, Bandar Wawasan, 54200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur.', 'https://goo.gl/maps/8mazjnsEBYLNE7SAA'),
('ZUS Coffee – IOI City Mall', 'L1-K204, First Floor, IOI City Mall 2, Lebuh IRC, IOI Resort City, 62502 Putrajaya', 'https://goo.gl/maps/Ye9w3xFSiig9n7oeA'),
('ZUS Coffee – Megah Rise Mall, PJ', 'Lot G-15, Ground Floor, Megah Rise Mall, Jalan SS 24/11, Taman Megah, 47301 Petaling Jaya', 'https://goo.gl/maps/b73K5H1Ek983SEfH8'),
('ZUS Coffee – BHP Jalan Maarof', '78, Jalan Ma’arof, Bangsar, 59000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://goo.gl/maps/U4H8v1DnV5TEEiTFA'),
('ZUS Coffee – The FLO Bandar Sri Damansara', 'GF-3, The Flo, Persiaran Perdana, Bandar Sri Damansara, 52200 Kuala Lumpur', 'https://goo.gl/maps/1hLReCzvSJRyFq8S9'),
('ZUS Coffee – AEON Mall Taman Equine Shopping Centre', 'Lot LG13, Lower Ground Floor, Aeon Taman Equine Shopping Centre, 2, Jalan Equine, Pusat Bandar Putra Permai, 43300 Seri Kembangan, Selangor', 'https://goo.gl/maps/pxDE1RrtdRdsRKyu9'),
('ZUS Coffee – Puncak Jalil', 'No 26 (Ground Floor), Jalan PUJ 3/13, Taman Puncak Jalil, 43300 Seri Kembangan, Selangor Darul Ehsan.', 'https://goo.gl/maps/qXAHbJcGuzigxw3V9'),
('ZUS Coffee – Banting', 'No 213 (Ground Floor), Jalan Sultan Abdul Samad, Bandar Banting, 42700 Banting, Selangor Darul Ehsan.', 'https://goo.gl/maps/cHENDvCbTrcD5J1a6'),
('ZUS Coffee – AEON Mall Shah Alam', 'Lot (KG10), AEON Mall Shah Alam, Jalan Akuatik 13/64, Seksyen 13, 40100 Shah Alam, Selangor', 'https://goo.gl/maps/WrZgREup9fWacaHWA'),
('ZUS Coffee – Datum Jelatek Mall', 'L1-K-09 & 07 (level 1), Datum Jelatek Mall, Jalan Enggang, Taman Keramat, 54200 Kuala Lumpur, Selangor.', 'https://goo.gl/maps/8fiwceaE2fBox6KB7'),
('ZUS Coffee – Taman Tas, Kuantan', 'B4 (Ground Floor), Lorong Pandan Damai 2/4, Taman Pandan Damai, 25150 Kuantan, Pahang Darul Makmur.', 'https://goo.gl/maps/TXqqmUfbj9bm1tQu6'),
('ZUS Coffee – Antara Gapi', 'No 15-G (Ground Floor), Jalan Gapi 1A/3, Perniagaan Antara Gapi, 48200 Serendah, Selangor Darul Ehsan.', 'https://goo.gl/maps/3kTB4G5CqSSug3Ew9'),
('ZUS Coffee – Shah Alam Seksyen 14 (Vista Alam)', 'F-G-29 (Ground Floor), Vista Alam, Jalan Ikhtisas, Seksyen 14, 40000 Shah Alam, Selangor Darul Ehsan', 'https://goo.gl/maps/id8tgjWsiwzczZdk9'),
('ZUS Coffee – Bandar Saujana Putra', 'No 19-G, Jalan SP 1/1, Bandar Saujana Putra, 42610 Jenjarom, Selangor Darul Ehsan.', 'https://goo.gl/maps/qK2Witykh7ddbfhU7'),
('ZUS Coffee – CALTEX Temiang', 'Lot 40766, Persiaran Sri Pulai 2, 70400 Seremban, Negeri Sembilan Darul Khusus.', 'https://goo.gl/maps/PmKWTyx7rdN945S79'),
('ZUS Coffee – SB Mall Sungai Buloh', 'G-17B, SB Mall, Bukit Rahman Putra, 47000 Sungai Buloh, Selangor', 'https://goo.gl/maps/fnrzKD1WCu8MzJZy9'),
('ZUS Coffee – Subang Bestari', 'No 3 (Ground Floor), Jalan Nova U5/N, Subang Bestari, 40150 Shah Alam, Selangor', 'https://goo.gl/maps/YKjfFkXmiFBfKM16A'),
('ZUS Coffee – Setia City Mall', 'L1-120, Level 1, Setia City Mall, Persiaran Setia Dagang, Setia Alam, 40170 Shah Alam, Selangor', 'https://goo.gl/maps/L7vyRinRvMNHPGhp8'),
('ZUS Coffee – Batang Kali', 'No 7 (Ground Floor), Jalan Mahagoni 7/1A, Seksyen 4, Perniagaan Jalan Mahagoni, 44300 Batang Kali, Selangor Darul Ehsan.', 'https://goo.gl/maps/RoHgYHj9fXx2CrUM9'),
('MENARA WORLDWIDE', 'Ground Floor, Menara Worldwide, 198, Jln Bukit Bintang, Kuala Lumpur, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://goo.gl/maps/fuQSdLxcxCAg5xZz9'),
('PUTRA HEIGHTS', 'No 31 (Ground Floor), Jalan Putra Mahkota 7/6c, Putra Point Commercial Centre, 47650 Subang Jaya, Selangor', 'https://goo.gl/maps/vqxPgJJMZJymU7MT9'),
('1 UTAMA SHOPPING CENTRE', '1 Utama Shopping Centre, Lot L2-SK9, 1, Lebuh Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor', 'https://goo.gl/maps/Z8rfW3FhuzkqGwJdA'),
('SAUJANA UTAMA', 'No. 23G, Taman, Jalan Bidara 10, Saujana Utama 3, 47000 Sungai Buloh, Selangor', 'https://goo.gl/maps/rnon9CMra17xr7c86'),
('DENAI ALAM', 'No 39, 1, Jln Elektron U16/D, Denai Alam, 40160 Shah Alam, Selangor', 'https://goo.gl/maps/2UDd59PdTC7sSwKR7'),
('BANDAR SERI COALFIELDS', 'No 32 (Ground Floor), Bandar Seri Coalfields, Jalan BSC 2B/2, 47000 Sungai Buloh, Selangor', 'https://goo.gl/maps/Au3qUb6U4pqjy1eE9'),
('TROPICANA GARDENS MALL', 'LOT 3F 47&48, Third Floor, Tropicana Gardens Mall, Jln PJU 3/21, Tropicana Indah, 47410 Petaling Jaya, Selangor', 'https://goo.gl/maps/qko2pt2EoSZbRvnC6'),
('LAKEFIELDS TRILLIUM', '58-G, Jalan Tasik Utama 5 Medan Niaga Tasik Damai, Sungai Besi, 57000 Kuala Lumpur', 'https://goo.gl/maps/dgsWKBS2813Q7Ehm8'),
('TAMAN SRI SERDANG, SERI KEMBANGAN', '3352 (Ground Floor), Jalan 18/32, Taman Sri Serdang, 43300 Seri Kembangan, Selangor', 'https://goo.gl/maps/hvcxbmcoVodhc5GT9'),
('IOI CONEZION', 'A-G-11, Connection Commercial, Persiaran IRC 3 IRC 3, IOI Resort City, 62502 Sepang, Wilayah Persekutuan Putrajaya', 'https://goo.gl/maps/w9o1bgCnSrPuMUSP7'),
('STARLING MALL', 'K-S-202, Second Floor The Starling Mall, 6, Jalan SS 21/37, Damansara Utama, 47400 Petaling Jaya, Selangor', 'https://goo.gl/maps/fEQKSKiF9N4rzEVk7'),
('SUBANG PERDANA', '27-G, Jalan Dinar E U3/E, Taman Subang Perdana, 40150 Shah Alam, Selangor', 'https://goo.gl/maps/kaPBHQ1bSss5Lcey7'),
('BANDAR SERI PUTRA', '13G, Jalan Seri Putra 1/2 Bandar Seri Putra Bangi, 43000 Kajang, Selangor', 'https://goo.gl/maps/RdVTpbpYL7ZCYCLP7'),
('SENTUL POINT', 'BC-G-08 Sentul Point Suite Apartments, Jalan Sentul Pasar, Sentul, 51000 Kuala Lumpur', 'https://goo.gl/maps/xfiWQ8XhKEhyQq1n9'),
('AMPANG SPECTRUM MALL', 'Lot CW-5, Cafe Walk, Ground Floor, Spectrum Shopping Mall', 'https://goo.gl/maps/q2bZdyKDYkNDbV2VA'),
('ZUS Coffee – DPulze Shopping Centre, Cyberjaya', 'Lot EX-GW-01A, Ground Floor, DPulze Shopping Centre, Persiaran Multimedia, Cyber 12, 63000 Cyberjaya', 'https://maps.app.goo.gl/BYiqE3Wdm35hAnVWA'),
('KOTA DAMANSARA', 'No. 27-1, Jalan PJU 5/12, Dataran Sunway, Kota Damansara, 47810 Petaling Jaya', 'https://goo.gl/maps/7w94urB4cH6zs9pU8'),
('ATRIA SHOPPING GALLERY', 'C01A, Concourse Floor, Atria Shopping Gallery, Jalan SS 22/23, Damansara Jaya 47400 Petaling Jaya.', 'https://goo.gl/maps/Z447kr2pPT44X2ScA'),
('BUKIT SENTOSA', '19G, Jalan Orkid 1F/2, Bukit Sentosa BS 1, 48300 Rawang, Selangor', 'https://goo.gl/maps/zxCcr3RNAdy3gobj7'),
('KOTA WARISAN', 'Unit 63-G, Jalan Warisan Sentral 1, Kota Warisan, Bandar Baru Salak Tinggi, 43900 Sepang, Selangor', 'https://goo.gl/maps/NrQciFrEzNer3mi5A'),
('SHAH ALAM SEKSYEN 13', 'No. 50, Jalan Renang 13/26, Tadisma Business Park, Seksyen 13, 40100 Shah Alam, Selangor', 'https://goo.gl/maps/xEbiPB9tS7erfrKS6'),
('ZUS Coffee – Sunway Gandaria, Bangi', 'UG-11 Sunway Gandaria, Jalan Pusat Bandar 2, Bandar Baru Bangi, Seksyen 9, 43650 Selangor', 'https://maps.app.goo.gl/hP9njvTKvXUyszMQ7'),
('RAWANG REEF', 'No. A13A-G, Jalan Reef 1/1, Pusat Perniagaan Reef, 48000 Rawang, Selangor', 'https://goo.gl/maps/oPNR5xyvTJnABbLw8'),
('PRIMA SRI GOMBAK', 'G-39, Jalan Prima SG 2, Prima Sri Gombak, 68100 Batu Caves, Selangor', 'https://goo.gl/maps/uLL2177jWKhyYbP57'),
('ZUS Coffee – Ecohill, Semenyih', 'C-06-01, Blok C, Pusat Komersial Dataran Ecohill, Jalan Ecohill 1/2, Setia Ecohill 43500 Semenyih, Selangor', 'https://maps.app.goo.gl/bEpkHP48dJJ3ZBSw9'),
('BANDAR BARU SELAYANG', '59, Jalan 2/16, Bandar Baru Selayang 68100 Batu Caves, Selangor', 'https://goo.gl/maps/jr1tADwxQfWhU3tt9'),
('BANDAR BUKIT RAJA', '13G, Jalan Rodat 2A/KU5, Bandar Bukit Raja 41050 Klang Selangor', 'https://goo.gl/maps/euN6UosVpihBmUgq6'),
('SETIA ALAM TP2', '36-G, Jalan Setia Utama AS U13/AS, Setia Alam, 40170 Shah Alam Selangor', 'https://goo.gl/maps/Yy4bN4o3t8KUV65W9'),
('SUNWAY PINNACLE', 'Unit G-02, Ground Floor, The Pinnacle Annexe, Persiaran Lagoon, Sunway City, 47500, Selangor', 'https://goo.gl/maps/zpkqHfttVscM32zz7'),
('KOTA KEMUNING', '1-17-1, No. 14, Persiaran Anggerik Vanilla, Kota Kemuning, Seksyen 31, 40460 Shah Alam, Selangor', 'https://goo.gl/maps/4zxXmFwCvu9xotAy5'),
('SHAH ALAM SEKSYEN 7', '24, Jalan Plumbum P7/P, Seksyen 7, 40000 Shah Alam, Selangor.', 'https://goo.gl/maps/m2GFHP9MnQs4VXAN8'),
('ZUS Coffee – MKH Boulevard, Kajang', 'Lot G-15, MKH Boulevard Kajang, Jalan Changkat, Bandar Kajang, 43000 Kajang Selangor.', 'https://maps.app.goo.gl/Rokmgi9ixdxmya7B7'),
('THE CURVE', 'K-G27-W, The Curve, Jalan PJU 7/3, Mutiara Damansara, 47820 Petaling Jaya, Selangor.', 'https://goo.gl/maps/5WpCbqwgiqmarPBQ9'),
('?CHERAS TRADER SQUARE', '83A-G, Jalan Dataran Cheras 4, Dataran Perniagaan Cheras, Balakong 43200 Selangor.', 'https://goo.gl/maps/57v1hCYjiF7CJvv36'),
('MAIN PLACE', 'GF-20, Main Place Mall, USJ 21, 47640 Subang Jaya, Selangor.', 'https://goo.gl/maps/LLSeca18BMWBuMTYA'),
('ZUS BUKIT TINGGI 2', 'No.55, Lorong Batu Nilam 21B, Bandar Bukit Tinggi 2, 41200 Klang Selangor Darul Ehsan.', 'https://goo.gl/maps/pcrkN8KNVyHHUr6q7'),
('ZUS Coffee – The Mines Shopping Mall', 'The Mines Shopping Mall, Level 3-21A, Jalan Dulang, Seri Kembangan, 43300 Selangor.', 'https://maps.app.goo.gl/sQUfwMYdT15j6Zj9A'),
('IOI RIO CITY', 'Lot 11-1, IOI RIO Office Park, 47100 Puchong, Selangor', 'https://goo.gl/maps/noRNa2WrthZToe5e7'),
('PUCHONG IOI MALL', 'Lot FK-02, First, Jalan Puchong, Bandar Puchong Jaya, 47170 Puchong, Selangor.', 'https://goo.gl/maps/WvTgKuDH2CQ98ihY6'),
('BANDAR MENJALARA', '37G, Jalan 3/62A, Bandar Menjalara, 52200 Kuala Lumpur', 'https://goo.gl/maps/LcbzA6bhyEGRCUKN9'),
('MASJID JAMEK', 'No. 45-1 & 45-2, Ground Floor, Leboh Ampang, Kuala Lumpur City Centre, 50100 Kuala Lumpur', 'https://goo.gl/maps/amJyLZ5Kwx2k3VGe6'),
('BANDAR SRI PERMAISURI', '11G, Jalan Dwitasik 1, Bandar Sri Permaisuri, 56000 Kuala Lumpur', 'https://goo.gl/maps/AEAGzQnW8btggXtx5'),
('PAVILION BUKIT JALIL', 'Lot P.1.05.00 Pavilion Bukit Jalil, Persiaran Jalil Utama, Bukit Jalil, 57000 Kuala Lumpur', 'https://goo.gl/maps/fDyasTvhs3JmQbzeA'),
('MYTOWN CHERAS', 'Mytown Shopping Mall, LOT G-K-015 & 016, Ground Floor, No.6, Jalan Cochrane, Seksyen 90, 55100 Kuala Lumpur', 'https://goo.gl/maps/Wnsi5P8APXzrSVsf7'),
('ZUS Coffee – Taman Bendahara, Kuala Selangor', 'No. 2, Jalan Bendahara 1/2A. Taman Bendahara 45000 Kuala Selangor.', 'https://maps.app.goo.gl/vVfbshkjfPtGWHUd8'),
('MID VALLEY MEGAMALL', 'SK-10, Second Floor, Mid Valley Megamall, Lingkaran Syed Putra, Midvalley City, 59200 Kuala Lumpur', 'https://goo.gl/maps/g4FugRDNNbutEqCEA'),
('ZUS Coffee – Fortune Centra, Kepong', 'G-16, Fortune Centra, 2, Jalan Metro Perdana Timur 6, Taman Usahawan Kepong, 52100 Kuala Lumpur', 'https://maps.app.goo.gl/kRSQA7sxDiTShDGL6'),
('FOUND8 KL SENTRAL', '5, Jalan Stesen Sentral, East Wing, Level 3 Kuala Lumpur Sentral 50470 Kuala Lumpur', 'https://goo.gl/maps/hXSR5K3Ae2L8t3o56'),
('PUBLIKA', 'Lot K1, G3, Publika Shopping Gallery, No. 1, Jalan Dutamas 1, Solaris Dutamas, 50480 Kuala Lumpur', 'https://goo.gl/maps/er2Frnbt1EsDipdG6'),
('PLAZA DAMAS', '60, Jalan Sri Hartamas 1, Taman Sri Hartamas, 50480 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', 'https://goo.gl/maps/758BwxAPbNza1Smb9'),
('SRI PETALING', 'Lot 36-J, Jalan Radin Anum, Sri Petaling, 57000 Kuala Lumpur', 'https://goo.gl/maps/CRBGyGYj6qpp4Qib6'),
('KL EAST MALL', 'Lot G2K-03A, KL East Mall, Jalan Lingkaran Tengah 2, Taman Sri Melati, 53100 Kuala Lumpur.', 'https://goo.gl/maps/iaBSM94FxsSZhrWf7'),
('DANAU KOTA', 'Lot 1-3, Danau Kota Kormesial, No. 1, Jalan 6A/6, Jalan Taman Ibu Kota, Taman Danau Kota, 53300 Kuala Lumpur.', 'https://goo.gl/maps/YZt1439jNkhU5RGu8'),
('EKOCHERAS MALL', 'S-63A, 2nd Floor, EkoCheras Mall, No 693, Batu 5, Jalan Cheras, 56000 Kuala Lumpur.', 'https://goo.gl/maps/tKrv7d1MDG1gonAj8'),
('ZUS Coffee – The Park Sky Residence, Bukit Jalil', '22, The Park Sky Residence @ Bukit Jalil City, Persiaran Jalil Utama, Bukit Jalil, 57000 Kuala Lumpur.', 'https://maps.app.goo.gl/LiYHGJBVCkLptukA9'),
('TAMAN DESA', 'No 11-0-10, Jalan 4/109F Danau Business Centre, Taman Danau Desa, 58100 Kuala Lumpur.', 'https://goo.gl/maps/ep7uUzN6Rwszehee7'),
('BINJAI 8 PREMIUM SOHO', 'G04, Pangsapuri Servis (Suite) Binjai 8 No, 2, Lorong Binjai, 50450 Kuala Lumpur.', 'https://g.page/ZusCoffee?share');